version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: potluck_db
    environment:
      POSTGRES_DB: potluck
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d potluck -h 127.0.0.1" ]
      interval: 5s
      timeout: 3s
      retries: 10
  springboot:
    build: .
    container_name: potluck_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/potluck
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      TZ: UTC
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: